name: flutter_wisata_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^19.3.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  http: ^1.2.1
  intl: ^0.19.0
  mobile_scanner: ^5.1.0
  path_provider: ^2.0.0
  permission_handler: ^12.0.1
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  timer_count_down: ^2.2.2
  url_launcher: ^6.1.7
  open_filex: ^4.1.0
  pdf: ^3.10.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/iconps.png"
  min_sdk_android: 21

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/nav/
    - assets/icons/payment/
    - assets/icons/settings/